/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb690",
        "on-secondary-fixed": "#341100",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#444749",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#74777f",
        "surface-tint": "#455f88",
        "secondary-container": "#fd761a",
        "on-primary": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "surface": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-container": "#9c9fa1",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "on-surface": "#0b1c30",
        "secondary-fixed": "#ffdbca",
        "primary-fixed-dim": "#adc7f7",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#43474e",
        "secondary": "#9d4300",
        "primary": "#002045",
        "inverse-surface": "#213145",
        "on-error-container": "#93000a",
        "on-secondary-container": "#5c2400",
        "on-primary-fixed": "#001b3c",
        "inverse-primary": "#adc7f7",
        "primary-container": "#1a365d",
        "outline-variant": "#c4c6cf",
        "tertiary": "#1d2123",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#e0e3e5",
        "tertiary-container": "#333638",
        "on-primary-fixed-variant": "#2d476f",
        "on-secondary-fixed-variant": "#783200",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-primary-container": "#86a0cd",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "background": "#f8f9ff",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dce9ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "margin-desktop": "48px",
        "stack-sm": "8px",
        "gutter": "24px",
        "section-gap": "80px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
